// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob/shorturl.proto

package protob

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetShortUrlRequest struct {
	OrigUrl              string   `protobuf:"bytes,1,opt,name=origUrl,proto3" json:"origUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShortUrlRequest) Reset()         { *m = GetShortUrlRequest{} }
func (m *GetShortUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetShortUrlRequest) ProtoMessage()    {}
func (*GetShortUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecde4c3e18691832, []int{0}
}

func (m *GetShortUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShortUrlRequest.Unmarshal(m, b)
}
func (m *GetShortUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShortUrlRequest.Marshal(b, m, deterministic)
}
func (m *GetShortUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShortUrlRequest.Merge(m, src)
}
func (m *GetShortUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetShortUrlRequest.Size(m)
}
func (m *GetShortUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShortUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShortUrlRequest proto.InternalMessageInfo

func (m *GetShortUrlRequest) GetOrigUrl() string {
	if m != nil {
		return m.OrigUrl
	}
	return ""
}

type GetShortUrlResponse struct {
	ShortUrl             string   `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShortUrlResponse) Reset()         { *m = GetShortUrlResponse{} }
func (m *GetShortUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetShortUrlResponse) ProtoMessage()    {}
func (*GetShortUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecde4c3e18691832, []int{1}
}

func (m *GetShortUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShortUrlResponse.Unmarshal(m, b)
}
func (m *GetShortUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShortUrlResponse.Marshal(b, m, deterministic)
}
func (m *GetShortUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShortUrlResponse.Merge(m, src)
}
func (m *GetShortUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetShortUrlResponse.Size(m)
}
func (m *GetShortUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShortUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetShortUrlResponse proto.InternalMessageInfo

func (m *GetShortUrlResponse) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

type GetOriginalUrlRequest struct {
	OrigUrl              string   `protobuf:"bytes,1,opt,name=origUrl,proto3" json:"origUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOriginalUrlRequest) Reset()         { *m = GetOriginalUrlRequest{} }
func (m *GetOriginalUrlRequest) String() string { return proto.CompactTextString(m) }
func (*GetOriginalUrlRequest) ProtoMessage()    {}
func (*GetOriginalUrlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecde4c3e18691832, []int{2}
}

func (m *GetOriginalUrlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOriginalUrlRequest.Unmarshal(m, b)
}
func (m *GetOriginalUrlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOriginalUrlRequest.Marshal(b, m, deterministic)
}
func (m *GetOriginalUrlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOriginalUrlRequest.Merge(m, src)
}
func (m *GetOriginalUrlRequest) XXX_Size() int {
	return xxx_messageInfo_GetOriginalUrlRequest.Size(m)
}
func (m *GetOriginalUrlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOriginalUrlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOriginalUrlRequest proto.InternalMessageInfo

func (m *GetOriginalUrlRequest) GetOrigUrl() string {
	if m != nil {
		return m.OrigUrl
	}
	return ""
}

type GetOriginalUrlResponse struct {
	ShortUrl             string   `protobuf:"bytes,1,opt,name=shortUrl,proto3" json:"shortUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOriginalUrlResponse) Reset()         { *m = GetOriginalUrlResponse{} }
func (m *GetOriginalUrlResponse) String() string { return proto.CompactTextString(m) }
func (*GetOriginalUrlResponse) ProtoMessage()    {}
func (*GetOriginalUrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ecde4c3e18691832, []int{3}
}

func (m *GetOriginalUrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOriginalUrlResponse.Unmarshal(m, b)
}
func (m *GetOriginalUrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOriginalUrlResponse.Marshal(b, m, deterministic)
}
func (m *GetOriginalUrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOriginalUrlResponse.Merge(m, src)
}
func (m *GetOriginalUrlResponse) XXX_Size() int {
	return xxx_messageInfo_GetOriginalUrlResponse.Size(m)
}
func (m *GetOriginalUrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOriginalUrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOriginalUrlResponse proto.InternalMessageInfo

func (m *GetOriginalUrlResponse) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*GetShortUrlRequest)(nil), "api.v1.GetShortUrlRequest")
	proto.RegisterType((*GetShortUrlResponse)(nil), "api.v1.GetShortUrlResponse")
	proto.RegisterType((*GetOriginalUrlRequest)(nil), "api.v1.GetOriginalUrlRequest")
	proto.RegisterType((*GetOriginalUrlResponse)(nil), "api.v1.GetOriginalUrlResponse")
}

func init() {
	proto.RegisterFile("protob/shorturl.proto", fileDescriptor_ecde4c3e18691832)
}

var fileDescriptor_ecde4c3e18691832 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xd2, 0x2f, 0xce, 0xc8, 0x2f, 0x2a, 0x29, 0x2d, 0xca, 0xd1, 0x03, 0xf3, 0x85, 0xd8,
	0x12, 0x0b, 0x32, 0xf5, 0xca, 0x0c, 0x95, 0xf4, 0xb8, 0x84, 0xdc, 0x53, 0x4b, 0x82, 0x41, 0x92,
	0xa1, 0x45, 0x39, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x12, 0x5c, 0xec, 0xf9, 0x45,
	0x99, 0xe9, 0xa1, 0x45, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x92, 0x21,
	0x97, 0x30, 0x8a, 0xfa, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x29, 0x2e, 0x8e, 0x62, 0xa8,
	0x18, 0x54, 0x07, 0x9c, 0xaf, 0x64, 0xc8, 0x25, 0xea, 0x9e, 0x5a, 0xe2, 0x5f, 0x94, 0x99, 0x9e,
	0x99, 0x97, 0x98, 0x43, 0x94, 0x2d, 0x26, 0x5c, 0x62, 0xe8, 0x5a, 0x08, 0x5b, 0x64, 0xb4, 0x94,
	0x91, 0x8b, 0x0b, 0xe6, 0xb2, 0xd4, 0x22, 0x21, 0x37, 0x2e, 0x6e, 0x24, 0xa7, 0x0a, 0x49, 0xe9,
	0x41, 0xbc, 0xac, 0x87, 0xe9, 0x5f, 0x29, 0x69, 0xac, 0x72, 0x50, 0x2b, 0xfd, 0xb9, 0xf8, 0x50,
	0x1d, 0x23, 0x24, 0x8b, 0xa4, 0x1c, 0xd3, 0x5f, 0x52, 0x72, 0xb8, 0xa4, 0x21, 0x06, 0x3a, 0x89,
	0x47, 0x89, 0x82, 0xdd, 0xac, 0x5b, 0x5a, 0x94, 0xa3, 0x9f, 0x5e, 0x54, 0x90, 0xac, 0x0f, 0x89,
	0xa3, 0x24, 0x36, 0x30, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x23, 0x84, 0xcd, 0xb4, 0xb4,
	0x01, 0x00, 0x00,
}
